#include <iostream>
/*
The sequence of triangle numbers is generated by adding the natural
numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

What is the value of the first triangle number to have over five hundred divisors?
*/
void f(long long int n)
{
	long long int sum = 0;

	for(long long int a = 1; a <= n; ++a){
		int count = 0;
		sum += a;
		for(long long int i = 1; i <= sum/2; ++i)
		{
			if(sum % i == 0) {
				std::cout << i << " ";
				++count;
			}
		}
		std::cout << count << std::endl;
		if(count >= 500) {
			std::cout << "number is " << n << std::endl;
			break;
		}
	}
}
int main()
{
	f(76576500);

	return 0;
}
